const FAQ = [
  // ---------- Identity ----------
  { keywords: ['what is asf', 'about asf', 'who are you', 'what is the fellowship', 'what does asf stand for'],
    answer: "ASF stands for Anglican Students' Fellowship. ASF UNIBEN/UBTH is a Christian fellowship for students of the University of Benin and UBTH, within the Anglican Communion." },
  { keywords: ['motto', 'slogan'],
    answer: 'Our motto is "Arise, Shine!" -- Isaiah 60 verse 1.' },
  { keywords: ['epithet', 'glorious family', 'nickname'],
    answer: 'ASF\u2019s epithet is "The Glorious Family."' },
  { keywords: ['original motto', 'first motto', 'old motto'],
    answer: 'At inception, ASF Uniben/UBTH\u2019s motto was "Equipping the saints for the work of the ministry." It was changed to "Arise, Shine!" in 1997, in line with the national constitution.' },
  { keywords: ['vision', 'mission', 'ancient landmark'],
    answer: 'Our vision is "Restoring the Ancient Landmark" (Proverbs 22:28, Jeremiah 6:16).' },
  { keywords: ['aims', 'objectives', 'purpose of asf'],
    answer: 'ASF exists to bring Anglican and non-Anglican students together for spiritual maturity and academic excellence, to keep students active in local churches during and after their studies, and to reconcile people to God through soul-winning.' },
  { keywords: ['doctrine', 'doctrinal basis', 'what do you believe', 'beliefs', 'creed'],
    answer: 'We hold to the biblical faith expressed in the Apostles\u2019 Creed, the Nicene Creed and the Thirty-Nine Articles of Religion -- emphasising personal knowledge of God, Jesus Christ as Lord and Saviour, and the infilling and work of the Holy Spirit.' },
  { keywords: ['emblem', 'logo', 'symbol', 'meaning of the colors', 'meaning of colours', 'what does the logo mean'],
    answer: 'The emblem shows an open Bible (the Word of God), a Cross (Christ\u2019s substitutionary death), a rising sun (our motto, Arise Shine!) and an academic cap (academic excellence), all in a circle (a global vision). Ox-blood on white represents sanctity through Christ\u2019s blood.' },
  { keywords: ['summary of asf', 'in a nutshell', 'sum up asf'],
    answer: 'In the constitution\u2019s own words: "Christian students, saved through the death of Christ, excelling in their academics and shining forth in the proclamation of the word of God to the whole world."' },
  { keywords: ['secret cult', 'cultism'],
    answer: 'No member of ASF may belong to any secret cult, no matter its stated aims or objectives.' },
  { keywords: ['relation to other churches', 'other denominations', 'affiliation'],
    answer: 'ASF is independent but cooperates with other Youth organisations within the Anglican Communion, and with any group that upholds its doctrinal basis. Branches work closely with their neighbouring Anglican churches and Diocese.' },
  { keywords: ['fellowship year'],
    answer: 'The fellowship year runs from the beginning of the First Semester to the end of the Second Semester of the same academic session.' },

  // ---------- National ASF ----------
  { keywords: ['national asf', 'asf nigeria', 'primate', 'when was asf nigeria founded'],
    answer: 'ASF Nigeria was conceived in 1997, received its official name on 2 May 1997, and was inaugurated on 21 November 1999 by The Most Rev. J. Abiodun, Primate of Nigeria. Late Ven. Olu Oshewa was among those who helped lay its foundation.' },
  { keywords: ['zones', 'how many zones'],
    answer: 'ASF Nigeria has four zones: the Eastern Zone, Western Zone, Northern Zone, and Southern Zone.' },
  { keywords: ['asfaan', 'jnec', 'nec', 'zec', 'cec', 'bec', 'hierarchy', 'national structure'],
    answer: 'ASF\u2019s national leadership hierarchy, from top to bottom, is: ASFAAN (Alumni Association Nigeria), JNEC (Joint National Executive Committee), NEC (National Executive Committee), ZEC (Zonal Executive Committee), CEC (Chapter Executive Committee), and BEC (Branch Executive Committee).' },
  { keywords: ['grand patron', 'national chaplain'],
    answer: 'ASF Nigeria\u2019s Grand Patron is His Grace, Most Rev\u2019d Henry Chukwudum Ndukuba, Metropolitan Primate of the Church of Nigeria. The National Chaplain is the Rt Rev\u2019d, Bishop of the Diocese of Jalingo.' },
  { keywords: ['how many branches', 'branches nationwide'],
    answer: 'ASF has over 100 branches across higher institutions in Nigeria.' },

  // ---------- History ----------
  { keywords: ['when was asf formed', 'history', 'founded', 'founding', 'who founded', 'formation'],
    answer: 'ASF Uniben/UBTH was formed in April 1994 to bridge the gap between youth and adults in the Anglican Communion, and to give Anglican students on campus a fellowship of their own rather than losing them to other campus fellowships.' },
  { keywords: ['bro jude', 'bro kingsley', 'edomwonyi', 'egwuonwu', 'founding fathers'],
    answer: 'Two young men caught the vision independently in 1994: Bro. Jude Edomwonyi started a fellowship called Anglican Students\u2019 Fellowship, and Bro. Kingsley Egwuonwu started one called Anglican Youth Fellowship. Both are now priests in the Anglican Communion.' },
  { keywords: ['first president', 'megaphone'],
    answer: 'ASF Uniben/UBTH\u2019s first President was Rev. K.O. Egwuonwu, who donated the fellowship\u2019s first public address system -- a megaphone.' },
  { keywords: ['anthem', 'theme song', 'we are one family', 'fellowship song'],
    answer: 'The fellowship song, "We Are One [Family]," was adopted in 1999.' },
  { keywords: ['hymn'],
    answer: 'ASF\u2019s special hymn is "Come Labour On!" (Hymns Ancient and Modern, 339).' },
  { keywords: ['psalm'],
    answer: 'ASF\u2019s special psalm is Psalm 15, "Lord, who shall dwell in thy tabernacle."' },
  { keywords: ['milestone', 'keyboard', 'drum set', 'important dates'],
    answer: 'Key milestones: first keyboard (1997, from 2nd Gift and Thanksgiving Day proceeds), first drum set (1998, from the fellowship\u2019s first student mini-launching), first "Great Rescue" revival (1995), first Gift Day (1996), first Sisters\u2019 Fellowship (1998), first Music Nite "Glorious Crescendo" (1998), and first Brothers\u2019 Day (1999).' },

  // ---------- Membership ----------
  { keywords: ['join', 'become a member', 'how do i register', 'membership', 'sign up', 'who can join'],
    answer: 'Membership is open to all students of the University and Teaching Hospital community -- you don\u2019t need to already be Anglican. Register on the site with your name, department, level, date of birth and location, and pick a ministry group.' },
  { keywords: ['not anglican', 'other denomination', 'do i need to be anglican'],
    answer: 'No -- the constitution explicitly welcomes both Anglican and non-Anglican students.' },
  { keywords: ['activities', 'what does asf do', 'what happens at meetings'],
    answer: 'ASF\u2019s activities include talks, Bible studies, prayer meetings, personal and mass evangelistic outreaches, and the activities of the various ministry groups.' },
  { keywords: ['change ministry group', 'switch group', 'leave a ministry group'],
    answer: 'Every member must belong to at least one, and at most two, ministry groups. To change or add a group, speak with your ministry group\u2019s leader -- this isn\u2019t currently self-service on the site.' },
  { keywords: ['is my information private', 'data privacy', 'who sees my details', 'who can see my data'],
    answer: 'Your date of birth and location are only visible to the site admins (GS and AGS) for member records -- not shown publicly.' },

  // ---------- EXCO structure & roles ----------
  { keywords: ['leader', 'exco', 'executive committee', 'who runs asf', 'exco members', 'exco positions'],
    answer: 'The Executive Committee (EXCO) has 20 positions: President, 1st VP (Ekehuan), 2nd VP (Ugbowo), General Secretary, Assistant General Secretary, Treasurer, Financial Secretary, Prayer Secretary, Bible Study Secretary, Evangelism Secretary, Organizing Secretary, Publicity Secretary, Academic Secretary, Welfare Secretary/Brothers\u2019 Coordinator, Welfare Secretary/Sisters\u2019 Coordinator, Part-time Students\u2019 Coordinator, UBTH Coordinator, Mission Secretary, Transport Secretary, and Alumni Representative.' },
  { keywords: ['what does the president do', 'president role', 'president function'],
    answer: 'The President is the highest officer and EXCO Chairman -- directs EXCO meetings, leads and coordinates all fellowship activities, presents the annual budget, convenes meetings through the GS, and represents the fellowship within and outside campus.' },
  { keywords: ['first vice president', 'vp1', 'vice president ekehuan'],
    answer: 'The First Vice President resides in Ekehuan Campus or its environs, and supervises/coordinates fellowship activities there, reporting to the President.' },
  { keywords: ['second vice president', 'vp2', 'vice president ugbowo'],
    answer: 'The Second Vice President resides in Ugbowo Campus, supervises activities there, and coordinates the Ministry Groups on behalf of the President.' },
  { keywords: ['what does the general secretary do', 'gs role', 'gs function'],
    answer: 'The General Secretary runs the Secretariat, summons meetings and takes minutes, prepares meeting agendas, invites approved speakers, gives fellowship announcements, and handles official correspondence.' },
  { keywords: ['what does the assistant general secretary do', 'ags role', 'ags function'],
    answer: 'The Assistant General Secretary assists the GS with secretariat duties, manages mail and the fellowship\u2019s post office box, and ensures the registration of new members -- which is exactly what this website\u2019s registration flow supports.' },
  { keywords: ['what does the treasurer do', 'treasurer role'],
    answer: 'The Treasurer collects monies from the Financial Secretary, issues receipts, banks fellowship funds within 7 days, pays EXCO-authorised claims, and keeps an impress account set by the EXCO.' },
  { keywords: ['what does the financial secretary do', 'financial secretary role'],
    answer: 'The Financial Secretary receives all monies collected at meetings, keeps proper records, hands funds to the Treasurer within 48 hours, and presents an annual financial report at the end of their tenure.' },
  { keywords: ['what does the prayer secretary do', 'prayer secretary role'],
    answer: 'The Prayer Secretary plans the fellowship\u2019s prayer programmes, represents ASF at prayer conferences/seminars, and works toward the spiritual soundness of members\u2019 prayer lives and prayer cells.' },
  { keywords: ['what does the bible study secretary do', 'bible study secretary role', 'bss role'],
    answer: 'The Bible Study Secretary draws up Bible study outlines with the Church Pastoral Aid Ministry (CPAM) and supervises the fellowship\u2019s Bible study meetings.' },
  { keywords: ['what does the evangelism secretary do', 'evangelism secretary role'],
    answer: 'The Evangelism Secretary plans and supervises evangelistic programmes across Ugbowo and Ekehuan, and oversees the "Catch Them Young" (CTY) programme.' },
  { keywords: ['what does the organizing secretary do', 'organizing secretary role'],
    answer: 'The Organizing Secretary arranges meeting venues (with TMU and the Aesthetic Unit), applies for and collects needed equipment, and supervises TMU and AU.' },
  { keywords: ['what does the publicity secretary do', 'publicity secretary role'],
    answer: 'The Publicity Secretary plans fellowship publications, acts as image-maker and spokesperson, and works with the Anglican Press Ministry and Publicity Unit on press releases, handbills, posters and notice boards.' },
  { keywords: ['what does the academic secretary do', 'academic secretary role'],
    answer: 'The Academic Secretary models academic excellence, organises study/discussion groups, provides academic welfare (counselling, past questions, textbooks), and evaluates members\u2019 study habits through interviews and seminars.' },
  { keywords: ['welfare secretary brothers', 'brothers coordinator'],
    answer: 'The Welfare Secretary/Brothers\u2019 Coordinator coordinates Hall Representatives with the Sisters\u2019 Coordinator, handles brothers\u2019 and visitors\u2019 welfare, and runs the Brothers\u2019 Forum.' },
  { keywords: ['welfare secretary sisters', 'sisters coordinator'],
    answer: 'The Welfare Secretary/Sisters\u2019 Coordinator coordinates Hall Representatives with the Brothers\u2019 Coordinator, handles sisters\u2019 and visitors\u2019 welfare, and runs the Sisters\u2019 Forum.' },
  { keywords: ['part-time students coordinator', 'part time coordinator'],
    answer: 'The Part-time Students\u2019 Coordinator must be a part-time student themself, and coordinates fellowship activities among part-time students.' },
  { keywords: ['ubth coordinator role', 'what does the ubth coordinator do'],
    answer: 'The UBTH Coordinator is elected from any UBTH school, reports to the President on day-to-day activities and welfare in UBTH schools, and resides in UBTH hostels or environs.' },
  { keywords: ['mission secretary'],
    answer: 'The Mission Secretary plans and leads fellowship missions to local congregations, nurtures missionary candidates, links ASF with mission societies, encourages chapel planting, and promotes village outreaches.' },
  { keywords: ['transport secretary'],
    answer: 'The Transport Secretary cares for and maintains fellowship vehicles and arranges transportation for fellowship activities.' },
  { keywords: ['alumni representative role'],
    answer: 'The Alumni Representative is the liaison officer between the Alumni body and the fellowship.' },

  // ---------- Leadership qualifications & elections ----------
  { keywords: ['how do i become a leader', 'run for position', 'qualify for leadership', 'exco qualification'],
    answer: 'To qualify for an EXCO position you must: be a full-time UNIBEN/UBTH student (except the Part-time Coordinator role), have been a registered member for at least 6 months, be active in your ministry group for 4 months, have completed the Discipleship Study Series (DSS), and pass screening/interview after nomination.' },
  { keywords: ['ministry group leader qualification', 'hall rep qualification'],
    answer: 'To become a ministry group leader or Hall Representative: be a properly admitted UNIBEN/UBTH student, have completed the DSS, have been active in that ministry group for at least 4 months, and pass nomination/interview. Hall Reps must also reside in the hall they represent.' },
  { keywords: ['dss', 'discipleship study series'],
    answer: 'The Discipleship Study Series (DSS) is a foundational study track -- completing it is a requirement for any leadership position, EXCO or ministry group.' },
  { keywords: ['election', 'nomination', 'how are leaders elected'],
    answer: 'Leaders are elected at the Annual Fellowship Meeting (AFM) by an Electoral Committee. Nominations happen up to 2 weeks before election; at least 10 nominees beyond the number of open offices go forward to a vote; screening/interviews follow; voting is by secret ballot; results are released within a week.' },
  { keywords: ['electoral committee'],
    answer: 'The Electoral Committee has 3 members appointed by the outgoing EXCO: a non-eligible outgoing EXCO member, a non-eligible non-EXCO fellowship member, and a senior friend. They can co-opt others (eligible members with 2+ sessions, alumni, senior friends) to help.' },
  { keywords: ['who can vote', 'voting eligibility'],
    answer: 'Only registered members who have been in the fellowship for at least 6 months can vote or be voted for.' },
  { keywords: ['tenure', 'how long do leaders serve', 'term length'],
    answer: 'Leaders hold office for one fellowship year, and are eligible for subsequent tenures up to a total of three years.' },
  { keywords: ['conduct of leaders', 'rules for leaders', 'leader requirements'],
    answer: 'After election, leaders must reside in UNIBEN/UBTH hostels or environs, be registered members of All Saints\u2019 Chapel UNIBEN or an Anglican church in Benin City, and attend services there. Leaders may not bear titles like "Pastor" or "Evangelist" -- ordained clergy cannot serve in leadership.' },
  { keywords: ['exco members ministry group leaders', 'can exco lead a ministry group'],
    answer: 'No -- EXCO members may not also be ministry group leaders.' },

  // ---------- Meetings ----------
  { keywords: ['meeting', 'when do you meet', 'service time', 'fellowship meeting'],
    answer: 'The fellowship meets on days set by the EXCO, never on Sundays. Ministry groups meet on days their own members agree on.' },
  { keywords: ['exco meeting', 'genco', 'combined meeting'],
    answer: 'EXCO meets as frequently as possible (quorum: 2/3 of members; emergency meetings need 1/3). Combined Ugbowo/Ekehuan EXCO meetings happen at least twice a semester. GENCO (EXCO + ministry group leaders + Hall Reps) meets as the President directs.' },
  { keywords: ['annual fellowship meeting', 'afm'],
    answer: 'The Annual Fellowship Meeting (AFM) is where the President\u2019s speech, the GS\u2019s report, and the Financial Secretary\u2019s account report are given, and elections are conducted. Its date is announced at least 2 fellowship meetings in advance.' },

  // ---------- Ministry groups ----------
  { keywords: ['ministry group', 'ministry groups', 'what groups', 'units', 'how many ministry groups'],
    answer: 'ASF has fifteen ministry groups and units, including prayer, outreach, discipleship (CPAM), music, drama, press, stewardship, children\u2019s ministry, ushering, media, decoration, transport, and care & visitation.' },
  { keywords: ['intercessory', 'prayer group', 'aim ministry'],
    answer: 'The Anglican Intercessory Ministry (AIM) is involved in prayer and intercession, working with the Prayer Secretary to organise prayer programmes.' },
  { keywords: ['campus and city outreach', 'outreach group', 'cco'],
    answer: 'Campus & City Outreach (CCO) is involved in evangelism within and outside the campus.' },
  { keywords: ['pastoral aid', 'cpam', 'discipleship unit', 'counselling unit', 'school visitation', 'abcdu'],
    answer: 'The Church Pastoral Aid Ministry (CPAM) has four units: Discipleship Unit (teaches new converts and Bible study), Counselling Unit (trains counsellors, provides spiritual counselling), School Visitation Unit (evangelism/pastoral work in schools), and the Anglican Baptism, Confirmation & Discipleship Unit.' },
  { keywords: ['children ministry', 'sunday school', 'acm'],
    answer: 'The Anglican Children Ministry (ACM) visits primary schools for evangelism, affiliates with other children\u2019s ministries for Sunday school teaching, and organises children\u2019s evangelism activities.' },
  { keywords: ['music ministry', 'choir', 'instrumentalist', 'amm'],
    answer: 'The Anglican Music Ministry (AMM) is the fellowship\u2019s choir -- training instrumentalists, composing songs, and ministering in song on and off campus.' },
  { keywords: ['drama ministry', 'adm', 'sketch', 'play'],
    answer: 'The Anglican Drama Ministry (ADM) trains dramatists and writes/performs plays ministering the gospel on and off campus.' },
  { keywords: ['press ministry', 'apm', 'library', 'tract', 'literature'],
    answer: 'The Anglican Press Ministry (APM) spreads Christian teaching through tracts and study materials, cares for the fellowship library, raises funds through literature sales, gives members a writing platform, and encourages persecuted Christians through correspondence.' },
  { keywords: ['stewardship ministry', 'asm', 'fundraising'],
    answer: 'The Anglican Stewardship Ministry (ASM) raises money for the fellowship through the year, including resource exhibitions and recreational fundraising.' },
  { keywords: ['ministry of helps', 'amh', 'hospital visit', 'orphanage'],
    answer: 'The Anglican Ministry of Helps (AMH) visits hospitals, orphanages and remand homes to share the gospel, encourage growth in Christ, and provide material aid.' },
  { keywords: ['masus', 'usher', 'sidemen', 'server'],
    answer: 'The Ministry of Anglican Sidemen, Ushers & Servers (MASUS) welcomes visitors, serves as ushers/sidemen in local churches, and handles property misplaced at meetings.' },
  { keywords: ['publicity unit', 'press release', 'poster'],
    answer: 'The Publicity Unit publicises fellowship activities and works with the Publicity Secretary on press releases, handbills, posters and notice boards.' },
  { keywords: ['technical unit', 'media unit', 'tmu', 'sound', 'equipment'],
    answer: 'The Technical and Media Unit (TMU) reports to the Organizing Secretary, maintains fellowship equipment, sets up for meetings/rehearsals, and covers meetings on media.' },
  { keywords: ['aesthetic unit', 'decoration', 'decor'],
    answer: 'The Aesthetic Unit reports to the Organizing Secretary and handles fellowship chairs, tables, and decorating/arranging venues.' },
  { keywords: ['transport unit', 'vehicle'],
    answer: 'The Transport Unit reports to the Transport Secretary, maintains fellowship vehicles, and arranges transportation for activities.' },
  { keywords: ['care and visitation', 'cvu', 'welfare visit', 'sick visit'],
    answer: 'The Care and Visitation Unit (CVU) visits new and old members, registers new members, follows up with them, visits the sick, and attends to members\u2019/ministers\u2019 welfare.' },
  { keywords: ['ministry group rules', 'ministry group general notes'],
    answer: 'Each ministry group affiliates with its parent body nationally, encourages similar groups in local churches, has activities approved by EXCO and supervised by the 2nd VP, transfers money to the Financial Secretary within 7 days, and elects its own leaders after EXCO elections.' },

  // ---------- Hall Reps & Secretariat ----------
  { keywords: ['hall rep', 'hall representative'],
    answer: 'Hall Representatives reside in the hall they\u2019re elected for, and their activities are supervised by the Welfare Secretaries.' },
  { keywords: ['secretariat'],
    answer: 'The Secretariat is for official fellowship purposes, supervised by the General Secretary. It can house fellowship members/visitors in time of need but is not a permanent residence, and occupants must follow biblical conduct guidelines.' },

  // ---------- Committees ----------
  { keywords: ['committee', 'budget committee', 'cty committee', 'dinner committee'],
    answer: 'ASF has committees of at least 3 EXCO-appointed members, including the Budget Committee, the Catch Them Young (CTY) Committee, the Dinner/Send-forth Committee, and the Electoral Committee.' },
  { keywords: ['budget committee'],
    answer: 'The Budget Committee has 5 EXCO-appointed members (including the Treasurer and Financial Secretary, chaired by the President) and presents the annual budget to EXCO at least 2 weeks before the budget launch.' },

  // ---------- Chaplain, Patrons, Staff Advisers ----------
  { keywords: ['chaplain'],
    answer: 'The Chaplain guides the fellowship spiritually, links ASF with the Diocese alongside the President and GS, represents ASF at Diocesan Synod, presides at EXCO dedications, attends key fellowship programmes, and is appointed by the Diocese for a renewable 4-year term.' },
  { keywords: ['patron', 'patrons'],
    answer: 'Patrons help generate funds, act as guardians/advisers, and assist ASF in achieving its aims. They\u2019re selected by the EXCO for a renewable 4-year term, must be committed Christians not in any secret cult, and married to one spouse.' },
  { keywords: ['staff adviser', 'staff advisers'],
    answer: 'ASF has 5 Staff Advisers (3 from UNIBEN, 2 from UBTH) who guide the fellowship, act as surety with the University, and help procure facilities. They\u2019re appointed by EXCO majority vote for a renewable 4-year term.' },

  // ---------- Alumni & Senior Friends ----------
  { keywords: ['alumni', 'graduated', 'no longer a student', 'asfaa'],
    answer: 'Graduated members who were registered ASF members become members of ASFAA (ASF Alumni Association), which appoints its own president/officers, sets its own rules, and assists the fellowship when called upon.' },
  { keywords: ['senior friends', 'sfaasf'],
    answer: 'The Senior Friends Association (SFAASF) includes the Chaplain, Patrons, Staff Advisers, all ASFAA members, and up to 3 honorary senior friends added each year. They receive the yearly budget and constitution, and may be invited to special programmes.' },

  // ---------- Discipline & Amendments ----------
  { keywords: ['discipline', 'misconduct', 'expulsion', 'suspension'],
    answer: 'Only the Chaplain determines what counts as "gross misconduct." Discipline/expulsion decisions need 3/4 of EXCO to agree; suspensions can\u2019t be indefinite (max 6 months); the accused gets a fair hearing; appeals go to the Chaplain.' },
  { keywords: ['amendment', 'change the constitution'],
    answer: 'Constitutional amendments must be proposed in writing to the Chaplain, Staff Advisers and SFAASF chairman, then approved by 3/4 of EXCO (with Staff Adviser input), the Chaplain, and finally 2/3 of members at a special fellowship meeting announced in advance.' },

  // ---------- Events & Giving ----------
  { keywords: ['catch them young', 'cty'],
    answer: 'Catch Them Young (CTY) is a programme at the start of every session aimed at reaching new intakes and growing fellowship membership.' },
  { keywords: ['asf sunday', 'education sunday', 'students day', 'lent'],
    answer: 'ASF Sunday (also called Education Sunday/Students\u2019 Day) falls on the second Sunday in Lent. The first week of Lent is a time of special fasting and prayer, with prayer requests sent to churches; ASF Sunday itself involves sharing fellowship reports with local churches and possible special collections.' },
  { keywords: ['gift day', 'music nite'],
    answer: 'ASF holds recurring events including Gift Day and Music Nite -- the first Music Nite, "Glorious Crescendo," was held in 1998.' },
  { keywords: ['give', 'donate', 'offering', 'tithe', 'fund', 'money', 'sources of income'],
    answer: 'ASF\u2019s income comes from members\u2019 tithes/offerings, special ASF Sunday church collections, Senior Friends\u2019 contributions, goodwill donations, ministry group fundraising (like ASM), and "all other ways the Lord chooses to provide" (Philippians 4:19).' },

  // ---------- Contact / admin / site ----------
  { keywords: ['contact', 'reach', 'ags', 'general secretary', 'admin', 'gs'],
    answer: "You can reach the GS on WhatsApp at +234 915 923 4422, or the AGS at +234 808 473 4611. Both numbers and the fellowship WhatsApp group link are on the Leadership page." },
  { keywords: ['whatsapp', 'group link', 'whatsapp group', 'community', 'chat group'],
    answer: "Yes -- ASF has a fellowship WhatsApp group where day-to-day updates and community happen. You'll find the join link on the Leadership page." },
  { keywords: ['announcement', 'notice', 'where do i see updates'],
    answer: 'Official notices from the GS/AGS are posted on the Announcements page -- check there once you\u2019re signed in.' },
  { keywords: ['forgot password', 'reset password', 'lost password', 'cant sign in', "can't log in"],
    answer: 'Tap "Forgot your password?" on the sign-in tab to get a reset link by email.' },
  { keywords: ['edit my profile', 'update my details', 'change my department', 'wrong information'],
    answer: 'Go to "My Profile" once signed in -- you can update your own department, level, date of birth, location and ministry group there directly.' },
  { keywords: ['is this site official', 'is this real', 'is this legit'],
    answer: 'Yes -- this site is run by the ASF UNIBEN/UBTH executive, with the GS and AGS as admins.' },
];

const FAQ_FALLBACK = "I don't have an answer for that yet. Try asking about membership, a specific ministry group or EXCO role, elections, meetings, giving, or the fellowship's history -- or reach out to the General Secretary / Assistant General Secretary directly.";
